---

- name: copy to server
  copy: src="{{item}}" dest="{{app_path}}/{{ ts }}/" mode=0644
  with_fileglob: backend*.jar

- name: unpacke application
  shell: warn=False chdir="{{app_path}}/{{ ts }}"  tar -xzf *.tgz ; rm -f *.tgz 

- name: stop docker application
  docker_container: state=absent name="{{ container_name }}"
  become: yes
  become_method: sudo

- name: start docker application
  docker_container: 
    name: "{{ container_name }}"
    image: java:8-jre-alpine
    entrypoint: java -jar /app/backend-*.jar
    volumes: 
      - "{{app_path}}/{{ ts }}/dist:/app"
    ports:
      - "9000:9000"
  become: yes
  become_method: sudo

- name: clean old release
  command: 'find {{app_path}} -maxdepth 1  -mindepth 1 -type d -ctime +3 -exec rm -rf {} \'