---

- name: copy to server
  copy: src=backend.jar dest="{{app_path}}/{{ ts }}/" mode=0644


- name: stop docker application
  docker_container: state=absent name="{{ container_name }}"
  become: yes
  become_method: sudo

- name: start docker application
  docker_container: 
    name: "{{ container_name }}"
    image: java:8-jre-alpine
    entrypoint: java -jar /app/backend.jar
    volumes: 
      - "{{app_path}}/{{ ts }}:/app"
    ports:
      - "9000:9000"
  become: yes
  become_method: sudo

- name: clean old release
  shell: 'find {{app_path}} -maxdepth 1  -mindepth 1 -type d -ctime +3 -exec rm -rf {} \;'