---

- name: copy to server
  copy: src="{{item}}" dest="{{app_path}}/{{ ts }}/" mode=0644
  with_fileglob: front*.tgz

- name: unpacke application
  shell: warn=False chdir="{{app_path}}/{{ ts }}"  tar -xzf *.tgz ; rm -f *.tgz 

- name: stop docker application
  docker_container: state=absent name="{{ container_name }}"
  become: yes
  become_method: sudo

- name: start docker application
  docker_container: 
    name: "{{ container_name }}"
    image: nginx:alpine
    volumes: 
      - "{{app_path}}/{{ ts }}/dist:/usr/share/nginx/html:ro"
    ports:
      - "8999:80"
  become: yes
  become_method: sudo

- name: clean old release
  command: 'find {{app_path}} -maxdepth 1  -mindepth 1 -type d -ctime +3 -exec rm -rf {} \'